version: '3.8'
services:
  sme-app:
    image: python:3.9-slim
    container_name: phan-mem-soan-ho-so
    working_dir: /app
    command: >
      sh -c "pip install streamlit docxtpl pandas openpyxl && streamlit run app.py --server.port=8501"
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      # Dòng dưới đây là quan trọng nhất: Map thư mục thật trên NAS vào app
      - "/volume1/BP.KinhDoanh/01_DangKy_DoanhNghiep:/app/output_nas"
    restart: always